//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indhu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public string feedbackid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string message { get; set; }
        public string type { get; set; }
        public string studentid { get; set; }
    
        public virtual feedback feedback1 { get; set; }
        public virtual feedback feedback2 { get; set; }
    }
}
