//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indhu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public Nullable<int> price { get; set; }
        public System.DateTime day { get; set; }
        public string type { get; set; }
        public string item { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    }
}
