//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indhu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class notice
    {
        public string nid { get; set; }
        public string studentid { get; set; }
        public string title { get; set; }
        public string message { get; set; }
    
        public virtual notice notice1 { get; set; }
        public virtual notice notice2 { get; set; }
    }
}
