//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indhu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomtable
    {
        public Nullable<int> capacity { get; set; }
        public string studentid { get; set; }
        public string RoomNo { get; set; }
    
        public virtual roomtable roomtable1 { get; set; }
        public virtual roomtable roomtable2 { get; set; }
    }
}
