//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace indhu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public string staffid { get; set; }
        public string staffname { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string address { get; set; }
        public string district { get; set; }
        public Nullable<int> pincode { get; set; }
        public string state { get; set; }
        public string email { get; set; }
        public Nullable<int> phonenumber { get; set; }
        public string dept { get; set; }
        public Nullable<System.DateTime> dateofjoininghostel { get; set; }
        public string hostelid { get; set; }
    
        public virtual staff staff1 { get; set; }
        public virtual staff staff2 { get; set; }
    }
}
